substitutions:
  _VERSION: "1.0.46"
  _DOCKER_VERSION: "1.0.46"

steps:
- name: 'gcr.io/its-artifact-commons/dotnet-sonar:2.2-4'
  entrypoint: 'bash'
  args: ['/workspace/GCloudBuild/sonar.bash']
  env: 
    - 'BASELINE_VERSION=1.0.2'  
    - 'SONAR_KEY=${_SONAR_KEY}'
    - 'BUILT_VERSION=${_VERSION}'
    - 'BRANCH_NAME=${BRANCH_NAME}'
    - 'COMMIT_SHA=${COMMIT_SHA}'
    - 'MAGNUM_FIREBASE_BUCKET=${_MAGNUM_FIREBASE_BUCKET}'
    - 'MAGNUM_FIREBASE_URL=${_MAGNUM_FIREBASE_URL}'
    - 'MAGNUM_FIREBASE_KEY=${_MAGNUM_FIREBASE_KEY}'
    - 'MAGNUM_DB_USERNAME=${_MAGNUM_DB_USERNAME}'
    - 'MAGNUM_DB_PASSWORD=${_MAGNUM_DB_PASSWORD}'    
    - 'MAGNUM_SMTP_PASSWORD=${_MAGNUM_SMTP_PASSWORD}'    
    - 'MAGNUM_SMTP_HOST=${_MAGNUM_SMTP_HOST}'
    - 'MAGNUM_SMTP_USER=${_MAGNUM_SMTP_USER}'
    - 'MAGNUM_SMTP_PORT=${_MAGNUM_SMTP_PORT}'
    
- name: 'microsoft/dotnet:2.2-sdk'
  entrypoint: 'dotnet'
  args: ['build', 'Magnum.sln', '-p:Version=${_VERSION}']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'VERSION_NUMBER=${_VERSION}', '-f', '/workspace/GCloudBuild/Dockerfile', '-t', 'gcr.io/${PROJECT_ID}/magnum-web:${_DOCKER_VERSION}', '/workspace' ]

images: ['gcr.io/${PROJECT_ID}/magnum-web:${_DOCKER_VERSION}']

