steps:

- name: 'ubuntu'
  volumes:
  - name: 'source'
    path: '/workspace'
  args: ['cat', '/workspace/sonar.bash']

- name: 'cassiofariasmachado/dotnet-sonarscanner:latest'
  entrypoint: '/workspace/sonar.bash'
  volumes:
  - name: 'source'
    path: '/workspace'
