steps:

- name: 'ubuntu'
  volumes:
  - name: 'source'
    path: '/source'
  args: ['cat', '/source/sonar.bash']
    
- name: 'cassiofariasmachado/dotnet-sonarscanner:latest'
  entrypoint: '/source/sonar.bash'
  volumes:
  - name: 'source'
    path: '/source'
