steps:


- name: 'microsoft/dotnet:2.2-sdk'
  entrypoint: 'dotnet'
  args: ['build', 'Magnum.sln', '-p:Version=1.0.1']

- name: 'cassiofariasmachado/dotnet-sonarscanner:latest'
  entrypoint: 'bash'
  args: ['/workspace/sonar.bash']
