steps:

- name: 'cassiofariasmachado/dotnet-sonarscanner:latest'
  args: [
          'dotnet', 'sonarscanner', 
          'begin', '/key:pjamenaja_magnum_web', '/o:pjamenaja', 
          '/v:1.0.0', '/d:sonar.host.url=https://sonarcloud.io', 
          '/d:sonar.branch.name=dev/test_cloud_build', 
          '/d:sonar.cs.opencover.reportsPaths=./coverage.opencover.xml', 
          '/d:sonar.javascript.exclusions=**/bootstrap/**,**/jquery/**,**/jquery-validation/**,**/jquery-validation-unobtrusive/** ',
          '/d:sonar.login=6b3024e6cc1576028a5bba761b1009ffb850b6f5', 
        ]

- name: microsoft/dotnet:2.1-sdk
  entrypoint: dotnet
  args: ['build', '-p:Version=1.0.0']

- name: 'cassiofariasmachado/dotnet-sonarscanner:latest'
  args: [
          'dotnet', 'sonarscanner',
          'end', '/d:sonar.login=6b3024e6cc1576028a5bba761b1009ffb850b6f5', 
        ]