steps:

- name: 'ubuntu'
  volumes:
  - name: 'source'
    path: '/source'
  args: ['cat', '/workspace/sonar.bash']

- name: 'cassiofariasmachado/dotnet-sonarscanner:latest'
  entrypoint: 'bash'
  args: ['/workspace/sonar.bash']
  volumes:
  - name: 'source'
    path: '/source'
